pipeline:
  identifier: Build_HayfordMD_reactcalculator_1704217005378
  name: Build reactcalculator
  orgIdentifier: default
  projectIdentifier: asdffsad
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github_OAuth_1703706465502
        repoName: HayfordMD/reactcalculator
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: Run
                  identifier: build_javascript_app
                  name: Build JavaScript App
                  spec:
                    shell: Sh
                    command: |-
                      echo "Welcome to Harness CI"
                      node --version
                      npm install
                      npm run build --if-present
                      npm test
          platform:
            arch: Amd64
            os: Linux
          runtime:
            spec: {}
            type: Cloud
        type: CI
